/*
 * LEIA RESTful API for AI
 * Leia API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@leia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.leia.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ApplicationTypes
 */
@JsonAdapter(ApplicationTypes.Adapter.class)
public enum ApplicationTypes {
  
  DEVELOPER("developer"),
  
  ADMIN("admin");

  private String value;

  ApplicationTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApplicationTypes fromValue(String value) {
    for (ApplicationTypes b : ApplicationTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ApplicationTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApplicationTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ApplicationTypes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ApplicationTypes.fromValue(value);
    }
  }
}

