/*
 * LEIA RESTful API for AI
 * Leia API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@leia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.leia.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.leia.client.model.ApplicationTypes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Application
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-11T17:16:03.438356+02:00[Europe/Paris]")
public class Application {
  public static final String SERIALIZED_NAME_API_KEY = "api_key";
  @SerializedName(SERIALIZED_NAME_API_KEY)
  private String apiKey;

  public static final String SERIALIZED_NAME_APPLICATION_NAME = "application_name";
  @SerializedName(SERIALIZED_NAME_APPLICATION_NAME)
  private String applicationName;

  public static final String SERIALIZED_NAME_APPLICATION_TYPE = "application_type";
  @SerializedName(SERIALIZED_NAME_APPLICATION_TYPE)
  private ApplicationTypes applicationType;

  public static final String SERIALIZED_NAME_CREATION_TIME = "creation_time";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private OffsetDateTime creationTime;

  public static final String SERIALIZED_NAME_DEDICATED_WORKERS = "dedicated_workers";
  @SerializedName(SERIALIZED_NAME_DEDICATED_WORKERS)
  private Boolean dedicatedWorkers;

  public static final String SERIALIZED_NAME_DEDICATED_WORKERS_MAX_MODELS = "dedicated_workers_max_models";
  @SerializedName(SERIALIZED_NAME_DEDICATED_WORKERS_MAX_MODELS)
  private Integer dedicatedWorkersMaxModels;

  public static final String SERIALIZED_NAME_DEDICATED_WORKERS_TTL = "dedicated_workers_ttl";
  @SerializedName(SERIALIZED_NAME_DEDICATED_WORKERS_TTL)
  private Integer dedicatedWorkersTtl;

  public static final String SERIALIZED_NAME_DEFAULT_JOB_CALLBACK_URL = "default_job_callback_url";
  @SerializedName(SERIALIZED_NAME_DEFAULT_JOB_CALLBACK_URL)
  private String defaultJobCallbackUrl;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_FIRST_NAME = "first_name";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_JOB_COUNTS = "job_counts";
  @SerializedName(SERIALIZED_NAME_JOB_COUNTS)
  private Object jobCounts;

  public static final String SERIALIZED_NAME_LAST_NAME = "last_name";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;


  public Application apiKey(String apiKey) {
    
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ghsrt6j94u6nbdw148j6t41nxf65bnwdt", value = "")

  public String getApiKey() {
    return apiKey;
  }


  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }


  public Application applicationName(String applicationName) {
    
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Example application", value = "")

  public String getApplicationName() {
    return applicationName;
  }


  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }


  public Application applicationType(ApplicationTypes applicationType) {
    
    this.applicationType = applicationType;
    return this;
  }

   /**
   * Get applicationType
   * @return applicationType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ApplicationTypes getApplicationType() {
    return applicationType;
  }


  public void setApplicationType(ApplicationTypes applicationType) {
    this.applicationType = applicationType;
  }


  public Application creationTime(OffsetDateTime creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-11-07T16:02:29.761Z", value = "")

  public OffsetDateTime getCreationTime() {
    return creationTime;
  }


  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }


  public Application dedicatedWorkers(Boolean dedicatedWorkers) {
    
    this.dedicatedWorkers = dedicatedWorkers;
    return this;
  }

   /**
   * Get dedicatedWorkers
   * @return dedicatedWorkers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getDedicatedWorkers() {
    return dedicatedWorkers;
  }


  public void setDedicatedWorkers(Boolean dedicatedWorkers) {
    this.dedicatedWorkers = dedicatedWorkers;
  }


  public Application dedicatedWorkersMaxModels(Integer dedicatedWorkersMaxModels) {
    
    this.dedicatedWorkersMaxModels = dedicatedWorkersMaxModels;
    return this;
  }

   /**
   * Get dedicatedWorkersMaxModels
   * @return dedicatedWorkersMaxModels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "")

  public Integer getDedicatedWorkersMaxModels() {
    return dedicatedWorkersMaxModels;
  }


  public void setDedicatedWorkersMaxModels(Integer dedicatedWorkersMaxModels) {
    this.dedicatedWorkersMaxModels = dedicatedWorkersMaxModels;
  }


  public Application dedicatedWorkersTtl(Integer dedicatedWorkersTtl) {
    
    this.dedicatedWorkersTtl = dedicatedWorkersTtl;
    return this;
  }

   /**
   * Get dedicatedWorkersTtl
   * @return dedicatedWorkersTtl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "200", value = "")

  public Integer getDedicatedWorkersTtl() {
    return dedicatedWorkersTtl;
  }


  public void setDedicatedWorkersTtl(Integer dedicatedWorkersTtl) {
    this.dedicatedWorkersTtl = dedicatedWorkersTtl;
  }


  public Application defaultJobCallbackUrl(String defaultJobCallbackUrl) {
    
    this.defaultJobCallbackUrl = defaultJobCallbackUrl;
    return this;
  }

   /**
   * Get defaultJobCallbackUrl
   * @return defaultJobCallbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://callback.example.com/leia_callback", value = "")

  public String getDefaultJobCallbackUrl() {
    return defaultJobCallbackUrl;
  }


  public void setDefaultJobCallbackUrl(String defaultJobCallbackUrl) {
    this.defaultJobCallbackUrl = defaultJobCallbackUrl;
  }


  public Application email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "contact@leia.io", required = true, value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public Application firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Firstname", required = true, value = "")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public Application id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "example_id", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Application jobCounts(Object jobCounts) {
    
    this.jobCounts = jobCounts;
    return this;
  }

   /**
   * Get jobCounts
   * @return jobCounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getJobCounts() {
    return jobCounts;
  }


  public void setJobCounts(Object jobCounts) {
    this.jobCounts = jobCounts;
  }


  public Application lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Lastname", required = true, value = "")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.apiKey, application.apiKey) &&
        Objects.equals(this.applicationName, application.applicationName) &&
        Objects.equals(this.applicationType, application.applicationType) &&
        Objects.equals(this.creationTime, application.creationTime) &&
        Objects.equals(this.dedicatedWorkers, application.dedicatedWorkers) &&
        Objects.equals(this.dedicatedWorkersMaxModels, application.dedicatedWorkersMaxModels) &&
        Objects.equals(this.dedicatedWorkersTtl, application.dedicatedWorkersTtl) &&
        Objects.equals(this.defaultJobCallbackUrl, application.defaultJobCallbackUrl) &&
        Objects.equals(this.email, application.email) &&
        Objects.equals(this.firstName, application.firstName) &&
        Objects.equals(this.id, application.id) &&
        Objects.equals(this.jobCounts, application.jobCounts) &&
        Objects.equals(this.lastName, application.lastName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, applicationName, applicationType, creationTime, dedicatedWorkers, dedicatedWorkersMaxModels, dedicatedWorkersTtl, defaultJobCallbackUrl, email, firstName, id, jobCounts, lastName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    applicationType: ").append(toIndentedString(applicationType)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    dedicatedWorkers: ").append(toIndentedString(dedicatedWorkers)).append("\n");
    sb.append("    dedicatedWorkersMaxModels: ").append(toIndentedString(dedicatedWorkersMaxModels)).append("\n");
    sb.append("    dedicatedWorkersTtl: ").append(toIndentedString(dedicatedWorkersTtl)).append("\n");
    sb.append("    defaultJobCallbackUrl: ").append(toIndentedString(defaultJobCallbackUrl)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobCounts: ").append(toIndentedString(jobCounts)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

