/*
 * LEIA RESTful API for AI
 * Leia API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sebastien.favre@docapost.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.leia.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.leia.client.model.FormatTypes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApplyBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-26T15:53:43.006+01:00[Europe/Paris]")
public class ApplyBody {
  public static final String SERIALIZED_NAME_CALLBACK_HEADERS = "callback_headers";
  @SerializedName(SERIALIZED_NAME_CALLBACK_HEADERS)
  private Object callbackHeaders;

  public static final String SERIALIZED_NAME_CALLBACK_URL = "callback_url";
  @SerializedName(SERIALIZED_NAME_CALLBACK_URL)
  private String callbackUrl;

  public static final String SERIALIZED_NAME_EXECUTE_AFTER_ID = "execute_after_id";
  @SerializedName(SERIALIZED_NAME_EXECUTE_AFTER_ID)
  private String executeAfterId;

  public static final String SERIALIZED_NAME_FORMAT_TYPE = "format_type";
  @SerializedName(SERIALIZED_NAME_FORMAT_TYPE)
  private FormatTypes formatType;

  public static final String SERIALIZED_NAME_MODEL_PARAMS = "model_params";
  @SerializedName(SERIALIZED_NAME_MODEL_PARAMS)
  private Object modelParams;

  public static final String SERIALIZED_NAME_PAGE_RANGE = "page_range";
  @SerializedName(SERIALIZED_NAME_PAGE_RANGE)
  private String pageRange;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;


  public ApplyBody callbackHeaders(Object callbackHeaders) {
    
    this.callbackHeaders = callbackHeaders;
    return this;
  }

   /**
   * Get callbackHeaders
   * @return callbackHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"header_1\":\"header_value_1\",\"header_2\":\"header_value_2\"}", value = "")

  public Object getCallbackHeaders() {
    return callbackHeaders;
  }


  public void setCallbackHeaders(Object callbackHeaders) {
    this.callbackHeaders = callbackHeaders;
  }


  public ApplyBody callbackUrl(String callbackUrl) {
    
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://www.example.com/callback_url", value = "")

  public String getCallbackUrl() {
    return callbackUrl;
  }


  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public ApplyBody executeAfterId(String executeAfterId) {
    
    this.executeAfterId = executeAfterId;
    return this;
  }

   /**
   * Get executeAfterId
   * @return executeAfterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "507f191e810c19729de860ec", value = "")

  public String getExecuteAfterId() {
    return executeAfterId;
  }


  public void setExecuteAfterId(String executeAfterId) {
    this.executeAfterId = executeAfterId;
  }


  public ApplyBody formatType(FormatTypes formatType) {
    
    this.formatType = formatType;
    return this;
  }

   /**
   * Get formatType
   * @return formatType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FormatTypes getFormatType() {
    return formatType;
  }


  public void setFormatType(FormatTypes formatType) {
    this.formatType = formatType;
  }


  public ApplyBody modelParams(Object modelParams) {
    
    this.modelParams = modelParams;
    return this;
  }

   /**
   * Get modelParams
   * @return modelParams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"model_param_1\":\"model_param_value_1\",\"model_param_2\":\"model_param_value_2\"}", value = "")

  public Object getModelParams() {
    return modelParams;
  }


  public void setModelParams(Object modelParams) {
    this.modelParams = modelParams;
  }


  public ApplyBody pageRange(String pageRange) {
    
    this.pageRange = pageRange;
    return this;
  }

   /**
   * Get pageRange
   * @return pageRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3:5", value = "")

  public String getPageRange() {
    return pageRange;
  }


  public void setPageRange(String pageRange) {
    this.pageRange = pageRange;
  }


  public ApplyBody tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "tag", value = "")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    this.tag = tag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplyBody applyBody = (ApplyBody) o;
    return Objects.equals(this.callbackHeaders, applyBody.callbackHeaders) &&
        Objects.equals(this.callbackUrl, applyBody.callbackUrl) &&
        Objects.equals(this.executeAfterId, applyBody.executeAfterId) &&
        Objects.equals(this.formatType, applyBody.formatType) &&
        Objects.equals(this.modelParams, applyBody.modelParams) &&
        Objects.equals(this.pageRange, applyBody.pageRange) &&
        Objects.equals(this.tag, applyBody.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackHeaders, callbackUrl, executeAfterId, formatType, modelParams, pageRange, tag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplyBody {\n");
    sb.append("    callbackHeaders: ").append(toIndentedString(callbackHeaders)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    executeAfterId: ").append(toIndentedString(executeAfterId)).append("\n");
    sb.append("    formatType: ").append(toIndentedString(formatType)).append("\n");
    sb.append("    modelParams: ").append(toIndentedString(modelParams)).append("\n");
    sb.append("    pageRange: ").append(toIndentedString(pageRange)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

