/*
 * LEIA RESTful API for AI
 * Leia API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@leia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.leia.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.leia.client.model.ModelInputTypes;
import io.leia.client.model.ModelTypes;
import io.leia.client.model.Speed;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-11T17:16:03.438356+02:00[Europe/Paris]")
public class Model {
  public static final String SERIALIZED_NAME_ALLOW_ALL_APPLICATIONS = "allow_all_applications";
  @SerializedName(SERIALIZED_NAME_ALLOW_ALL_APPLICATIONS)
  private Boolean allowAllApplications;

  public static final String SERIALIZED_NAME_ALLOWED_APPLICATION_IDS = "allowed_application_ids";
  @SerializedName(SERIALIZED_NAME_ALLOWED_APPLICATION_IDS)
  private List<String> allowedApplicationIds = null;

  public static final String SERIALIZED_NAME_APPLICATION_ID = "application_id";
  @SerializedName(SERIALIZED_NAME_APPLICATION_ID)
  private String applicationId;

  public static final String SERIALIZED_NAME_CREATION_TIME = "creation_time";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private OffsetDateTime creationTime;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DOCUMENTATION = "documentation";
  @SerializedName(SERIALIZED_NAME_DOCUMENTATION)
  private String documentation;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_INPUT_TYPES = "input_types";
  @SerializedName(SERIALIZED_NAME_INPUT_TYPES)
  private List<ModelInputTypes> inputTypes = new ArrayList<>();

  public static final String SERIALIZED_NAME_MD5SUM = "md5sum";
  @SerializedName(SERIALIZED_NAME_MD5SUM)
  private String md5sum;

  public static final String SERIALIZED_NAME_MODEL_CLAZZ = "model_clazz";
  @SerializedName(SERIALIZED_NAME_MODEL_CLAZZ)
  private String modelClazz;

  public static final String SERIALIZED_NAME_MODEL_MODULE = "model_module";
  @SerializedName(SERIALIZED_NAME_MODEL_MODULE)
  private String modelModule;

  public static final String SERIALIZED_NAME_MODEL_TYPE = "model_type";
  @SerializedName(SERIALIZED_NAME_MODEL_TYPE)
  private ModelTypes modelType;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OUTPUT_FORMAT = "output_format";
  @SerializedName(SERIALIZED_NAME_OUTPUT_FORMAT)
  private Object outputFormat;

  public static final String SERIALIZED_NAME_SHORT_NAME = "short_name";
  @SerializedName(SERIALIZED_NAME_SHORT_NAME)
  private String shortName;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private BigDecimal size;

  public static final String SERIALIZED_NAME_SPEED = "speed";
  @SerializedName(SERIALIZED_NAME_SPEED)
  private Speed speed;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public static final String SERIALIZED_NAME_TTL = "ttl";
  @SerializedName(SERIALIZED_NAME_TTL)
  private BigDecimal ttl;


  public Model allowAllApplications(Boolean allowAllApplications) {
    
    this.allowAllApplications = allowAllApplications;
    return this;
  }

   /**
   * Get allowAllApplications
   * @return allowAllApplications
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getAllowAllApplications() {
    return allowAllApplications;
  }


  public void setAllowAllApplications(Boolean allowAllApplications) {
    this.allowAllApplications = allowAllApplications;
  }


  public Model allowedApplicationIds(List<String> allowedApplicationIds) {
    
    this.allowedApplicationIds = allowedApplicationIds;
    return this;
  }

  public Model addAllowedApplicationIdsItem(String allowedApplicationIdsItem) {
    if (this.allowedApplicationIds == null) {
      this.allowedApplicationIds = new ArrayList<>();
    }
    this.allowedApplicationIds.add(allowedApplicationIdsItem);
    return this;
  }

   /**
   * Get allowedApplicationIds
   * @return allowedApplicationIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAllowedApplicationIds() {
    return allowedApplicationIds;
  }


  public void setAllowedApplicationIds(List<String> allowedApplicationIds) {
    this.allowedApplicationIds = allowedApplicationIds;
  }


  public Model applicationId(String applicationId) {
    
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "example_id", value = "")

  public String getApplicationId() {
    return applicationId;
  }


  public void setApplicationId(String applicationId) {
    this.applicationId = applicationId;
  }


  public Model creationTime(OffsetDateTime creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2018-11-07T16:02:29.761Z", required = true, value = "")

  public OffsetDateTime getCreationTime() {
    return creationTime;
  }


  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }


  public Model description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "This is a description of my model", value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Model documentation(String documentation) {
    
    this.documentation = documentation;
    return this;
  }

   /**
   * Get documentation
   * @return documentation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Documentation of the model", value = "")

  public String getDocumentation() {
    return documentation;
  }


  public void setDocumentation(String documentation) {
    this.documentation = documentation;
  }


  public Model id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "example_id", required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Model inputTypes(List<ModelInputTypes> inputTypes) {
    
    this.inputTypes = inputTypes;
    return this;
  }

  public Model addInputTypesItem(ModelInputTypes inputTypesItem) {
    this.inputTypes.add(inputTypesItem);
    return this;
  }

   /**
   * Get inputTypes
   * @return inputTypes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<ModelInputTypes> getInputTypes() {
    return inputTypes;
  }


  public void setInputTypes(List<ModelInputTypes> inputTypes) {
    this.inputTypes = inputTypes;
  }


  public Model md5sum(String md5sum) {
    
    this.md5sum = md5sum;
    return this;
  }

   /**
   * The MD5 sum of the model
   * @return md5sum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The MD5 sum of the model")

  public String getMd5sum() {
    return md5sum;
  }


  public void setMd5sum(String md5sum) {
    this.md5sum = md5sum;
  }


  public Model modelClazz(String modelClazz) {
    
    this.modelClazz = modelClazz;
    return this;
  }

   /**
   * The Python class name of the model
   * @return modelClazz
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The Python class name of the model")

  public String getModelClazz() {
    return modelClazz;
  }


  public void setModelClazz(String modelClazz) {
    this.modelClazz = modelClazz;
  }


  public Model modelModule(String modelModule) {
    
    this.modelModule = modelModule;
    return this;
  }

   /**
   * The Python module ghosting the code for the model
   * @return modelModule
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The Python module ghosting the code for the model")

  public String getModelModule() {
    return modelModule;
  }


  public void setModelModule(String modelModule) {
    this.modelModule = modelModule;
  }


  public Model modelType(ModelTypes modelType) {
    
    this.modelType = modelType;
    return this;
  }

   /**
   * Get modelType
   * @return modelType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ModelTypes getModelType() {
    return modelType;
  }


  public void setModelType(ModelTypes modelType) {
    this.modelType = modelType;
  }


  public Model name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "my_classification_model", required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Model outputFormat(Object outputFormat) {
    
    this.outputFormat = outputFormat;
    return this;
  }

   /**
   * Get outputFormat
   * @return outputFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"string\"]", value = "")

  public Object getOutputFormat() {
    return outputFormat;
  }


  public void setOutputFormat(Object outputFormat) {
    this.outputFormat = outputFormat;
  }


  public Model shortName(String shortName) {
    
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "classif", value = "")

  public String getShortName() {
    return shortName;
  }


  public void setShortName(String shortName) {
    this.shortName = shortName;
  }


  public Model size(BigDecimal size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getSize() {
    return size;
  }


  public void setSize(BigDecimal size) {
    this.size = size;
  }


  public Model speed(Speed speed) {
    
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Speed getSpeed() {
    return speed;
  }


  public void setSpeed(Speed speed) {
    this.speed = speed;
  }


  public Model tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public Model addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public Model ttl(BigDecimal ttl) {
    
    this.ttl = ttl;
    return this;
  }

   /**
   * The TTL of the workers hosting this model
   * @return ttl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The TTL of the workers hosting this model")

  public BigDecimal getTtl() {
    return ttl;
  }


  public void setTtl(BigDecimal ttl) {
    this.ttl = ttl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model model = (Model) o;
    return Objects.equals(this.allowAllApplications, model.allowAllApplications) &&
        Objects.equals(this.allowedApplicationIds, model.allowedApplicationIds) &&
        Objects.equals(this.applicationId, model.applicationId) &&
        Objects.equals(this.creationTime, model.creationTime) &&
        Objects.equals(this.description, model.description) &&
        Objects.equals(this.documentation, model.documentation) &&
        Objects.equals(this.id, model.id) &&
        Objects.equals(this.inputTypes, model.inputTypes) &&
        Objects.equals(this.md5sum, model.md5sum) &&
        Objects.equals(this.modelClazz, model.modelClazz) &&
        Objects.equals(this.modelModule, model.modelModule) &&
        Objects.equals(this.modelType, model.modelType) &&
        Objects.equals(this.name, model.name) &&
        Objects.equals(this.outputFormat, model.outputFormat) &&
        Objects.equals(this.shortName, model.shortName) &&
        Objects.equals(this.size, model.size) &&
        Objects.equals(this.speed, model.speed) &&
        Objects.equals(this.tags, model.tags) &&
        Objects.equals(this.ttl, model.ttl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowAllApplications, allowedApplicationIds, applicationId, creationTime, description, documentation, id, inputTypes, md5sum, modelClazz, modelModule, modelType, name, outputFormat, shortName, size, speed, tags, ttl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model {\n");
    sb.append("    allowAllApplications: ").append(toIndentedString(allowAllApplications)).append("\n");
    sb.append("    allowedApplicationIds: ").append(toIndentedString(allowedApplicationIds)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputTypes: ").append(toIndentedString(inputTypes)).append("\n");
    sb.append("    md5sum: ").append(toIndentedString(md5sum)).append("\n");
    sb.append("    modelClazz: ").append(toIndentedString(modelClazz)).append("\n");
    sb.append("    modelModule: ").append(toIndentedString(modelModule)).append("\n");
    sb.append("    modelType: ").append(toIndentedString(modelType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    outputFormat: ").append(toIndentedString(outputFormat)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    ttl: ").append(toIndentedString(ttl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

