/*
 * LEIA RESTful API for AI
 * Leia API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@leia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.leia.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TrainBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-11T17:16:03.438356+02:00[Europe/Paris]")
public class TrainBody {
  public static final String SERIALIZED_NAME_CALLBACK_HEADERS = "callback_headers";
  @SerializedName(SERIALIZED_NAME_CALLBACK_HEADERS)
  private Object callbackHeaders;

  public static final String SERIALIZED_NAME_CALLBACK_URL = "callback_url";
  @SerializedName(SERIALIZED_NAME_CALLBACK_URL)
  private String callbackUrl;

  public static final String SERIALIZED_NAME_DOCUMENTS_TAG = "documents_tag";
  @SerializedName(SERIALIZED_NAME_DOCUMENTS_TAG)
  private String documentsTag;

  public static final String SERIALIZED_NAME_EXECUTE_AFTER_ID = "execute_after_id";
  @SerializedName(SERIALIZED_NAME_EXECUTE_AFTER_ID)
  private String executeAfterId;

  public static final String SERIALIZED_NAME_MODEL_MODULE = "model_module";
  @SerializedName(SERIALIZED_NAME_MODEL_MODULE)
  private String modelModule;

  public static final String SERIALIZED_NAME_MODEL_NAME = "model_name";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  private String modelName;

  public static final String SERIALIZED_NAME_MODEL_PARAMS = "model_params";
  @SerializedName(SERIALIZED_NAME_MODEL_PARAMS)
  private Object modelParams;


  public TrainBody callbackHeaders(Object callbackHeaders) {
    
    this.callbackHeaders = callbackHeaders;
    return this;
  }

   /**
   * Get callbackHeaders
   * @return callbackHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"header_1\":\"header_value_1\",\"header_2\":\"header_value_2\"}", value = "")

  public Object getCallbackHeaders() {
    return callbackHeaders;
  }


  public void setCallbackHeaders(Object callbackHeaders) {
    this.callbackHeaders = callbackHeaders;
  }


  public TrainBody callbackUrl(String callbackUrl) {
    
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://www.example.com/callback_url", value = "")

  public String getCallbackUrl() {
    return callbackUrl;
  }


  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public TrainBody documentsTag(String documentsTag) {
    
    this.documentsTag = documentsTag;
    return this;
  }

   /**
   * Get documentsTag
   * @return documentsTag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "tag", value = "")

  public String getDocumentsTag() {
    return documentsTag;
  }


  public void setDocumentsTag(String documentsTag) {
    this.documentsTag = documentsTag;
  }


  public TrainBody executeAfterId(String executeAfterId) {
    
    this.executeAfterId = executeAfterId;
    return this;
  }

   /**
   * Get executeAfterId
   * @return executeAfterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "example_id", value = "")

  public String getExecuteAfterId() {
    return executeAfterId;
  }


  public void setExecuteAfterId(String executeAfterId) {
    this.executeAfterId = executeAfterId;
  }


  public TrainBody modelModule(String modelModule) {
    
    this.modelModule = modelModule;
    return this;
  }

   /**
   * Get modelModule
   * @return modelModule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "leia.models.text.classifier.fasttext.v1", value = "")

  public String getModelModule() {
    return modelModule;
  }


  public void setModelModule(String modelModule) {
    this.modelModule = modelModule;
  }


  public TrainBody modelName(String modelName) {
    
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "test.model", value = "")

  public String getModelName() {
    return modelName;
  }


  public void setModelName(String modelName) {
    this.modelName = modelName;
  }


  public TrainBody modelParams(Object modelParams) {
    
    this.modelParams = modelParams;
    return this;
  }

   /**
   * Get modelParams
   * @return modelParams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"model_param_1\":\"model_param_value_1\",\"model_param_2\":\"model_param_value_2\"}", value = "")

  public Object getModelParams() {
    return modelParams;
  }


  public void setModelParams(Object modelParams) {
    this.modelParams = modelParams;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainBody trainBody = (TrainBody) o;
    return Objects.equals(this.callbackHeaders, trainBody.callbackHeaders) &&
        Objects.equals(this.callbackUrl, trainBody.callbackUrl) &&
        Objects.equals(this.documentsTag, trainBody.documentsTag) &&
        Objects.equals(this.executeAfterId, trainBody.executeAfterId) &&
        Objects.equals(this.modelModule, trainBody.modelModule) &&
        Objects.equals(this.modelName, trainBody.modelName) &&
        Objects.equals(this.modelParams, trainBody.modelParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackHeaders, callbackUrl, documentsTag, executeAfterId, modelModule, modelName, modelParams);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainBody {\n");
    sb.append("    callbackHeaders: ").append(toIndentedString(callbackHeaders)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    documentsTag: ").append(toIndentedString(documentsTag)).append("\n");
    sb.append("    executeAfterId: ").append(toIndentedString(executeAfterId)).append("\n");
    sb.append("    modelModule: ").append(toIndentedString(modelModule)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelParams: ").append(toIndentedString(modelParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

