/*
 * LEIA RESTful API for AI
 * Leia API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@leia.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.leia.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TransformTypes
 */
@JsonAdapter(TransformTypes.Adapter.class)
public enum TransformTypes {
  
  TEXT("text"),
  
  TEXT_TREE("text_tree"),
  
  IMAGE("image"),
  
  AUTOROTATE("autorotate"),
  
  TRIM("trim"),
  
  MERGE("merge"),
  
  SPLIT("split"),
  
  TRANSCODE("transcode");

  private String value;

  TransformTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransformTypes fromValue(String value) {
    for (TransformTypes b : TransformTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TransformTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransformTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TransformTypes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TransformTypes.fromValue(value);
    }
  }
}

